
begin;
update organisationunit set name  = 'AGR-ASC Associated Clinic Agra', shortname  = 'AGR-ASC Associated Clinic Agra' where organisationunitid = 375161;
update organisationunit set name  = 'AGR-CBD Agra', shortname  = 'AGR-CBD Agra' where organisationunitid = 14269;
update organisationunit set name  = 'AGR-ORS Bodala', shortname  = 'AGR-ORS Bodala' where organisationunitid = 14595;
update organisationunit set name  = 'AGR-ORS Gari Bhadoriya', shortname  = 'AGR-ORS Gari Bhadoriya' where organisationunitid = 14596;
update organisationunit set name  = 'AGR-ORS Lohamandi', shortname  = 'AGR-ORS Lohamandi' where organisationunitid = 14594;
update organisationunit set name  = 'AGR-RH Shahganj RHFPC', shortname  = 'AGR-RH Shahganj RHFPC' where organisationunitid = 14593;
update organisationunit set name  = 'AGR-OA Outside Agencies', shortname  = 'AGR-OA Outside Agencies' where organisationunitid = 24246;
update organisationunit set name  = 'AGR-PMP', shortname  = 'AGR-PMP' where organisationunitid = 24245;
update organisationunit set name  = 'AHM-ASC Associated Clinic Ahmedabad ', shortname  = 'AHM-ASC Associated Clinic Ahmedabad ' where organisationunitid = 375203;
update organisationunit set name  = 'AHM-CBD Kankaria', shortname  = 'AHM-CBD Kankaria' where organisationunitid = 14409;
update organisationunit set name  = 'AHM-CBD Madhupura-RH', shortname  = 'AHM-CBD Madhupura-RH' where organisationunitid = 14408;
update organisationunit set name  = 'AHM-CBD Madhupura-UH', shortname  = 'AHM-CBD Madhupura-UH' where organisationunitid = 14411;
update organisationunit set name  = 'AHM-CBD Raikhad', shortname  = 'AHM-CBD Raikhad' where organisationunitid = 14412;
update organisationunit set name  = 'AHM-CBD Thakkarbapanagar', shortname  = 'AHM-CBD Thakkarbapanagar' where organisationunitid = 14413;
update organisationunit set name  = 'AHM-ORS Kankaria', shortname  = 'AHM-ORS Kankaria' where organisationunitid = 14707;
update organisationunit set name  = 'AHM-UH Madhupura UFWC', shortname  = 'AHM-UH Madhupura UFWC' where organisationunitid = 14598;
update organisationunit set name  = 'AHM-UH Raikhad UFWC', shortname  = 'AHM-UH Raikhad UFWC' where organisationunitid = 14599;
update organisationunit set name  = 'AHM-UH Thakkarnagar UFWC', shortname  = 'AHM-UH Thakkarnagar UFWC' where organisationunitid = 14600;
update organisationunit set name  = 'AHM-RH Madhupura RHFPC', shortname  = 'AHM-RH Madhupura RHFPC' where organisationunitid = 14616;
update organisationunit set name  = 'AHM-OA Outside Agencies', shortname  = 'AHM-OA Outside Agencies' where organisationunitid = 24901;
update organisationunit set name  = 'AHM-PMP', shortname  = 'AHM-PMP' where organisationunitid = 24845;
update organisationunit set name  = 'BAL-ASC Associated Clinic Ballari', shortname  = 'BAL-ASC Associated Clinic Ballari' where organisationunitid = 375306;
update organisationunit set name  = 'BAL-CBD Ballari', shortname  = 'BAL-CBD Ballari' where organisationunitid = 24673;
update organisationunit set name  = 'BAL-ORS Ballari', shortname  = 'BAL-ORS Ballari' where organisationunitid = 20527;
update organisationunit set name  = 'BAL-RH Nalla Cheru RHFPC', shortname  = 'BAL-RH Nalla Cheru RHFPC' where organisationunitid = 20528;
update organisationunit set name  = 'BAL-OA Outside Agencies', shortname  = 'BAL-OA Outside Agencies' where organisationunitid = 24913;
update organisationunit set name  = 'BAL-PMP', shortname  = 'BAL-PMP' where organisationunitid = 24846;
update organisationunit set name  = 'BAR-CBD Barwani', shortname  = 'BAR-CBD Barwani' where organisationunitid = 20503;
update organisationunit set name  = 'BAR-ORS Barwani', shortname  = 'BAR-ORS Barwani' where organisationunitid = 20502;
update organisationunit set name  = 'BAR-OA Outside Agencies', shortname  = 'BAR-OA Outside Agencies' where organisationunitid = 24933;
update organisationunit set name  = 'BAR-PMP', shortname  = 'BAR-PMP' where organisationunitid = 24850;
update organisationunit set name  = 'BEL-ASC Associated Clinic Belagavi', shortname  = 'BEL-ASC Associated Clinic Belagavi' where organisationunitid = 375483;
update organisationunit set name  = 'BEL-CBD Belagavi', shortname  = 'BEL-CBD Belagavi' where organisationunitid = 24672;
update organisationunit set name  = 'BEL-ORS Belagavi', shortname  = 'BEL-ORS Belagavi' where organisationunitid = 20522;
update organisationunit set name  = 'BEL-RH Hindwadi RHFPC', shortname  = 'BEL-RH Hindwadi RHFPC' where organisationunitid = 20515;
update organisationunit set name  = 'BEL-OA Outside Agencies', shortname  = 'BEL-OA Outside Agencies' where organisationunitid = 24920;
update organisationunit set name  = 'BEL-PMP', shortname  = 'BEL-PMP' where organisationunitid = 24857;
update organisationunit set name  = 'BEN-ASC Associated Clinic Bengaluru', shortname  = 'BEN-ASC Associated Clinic Bengaluru' where organisationunitid = 375276;
update organisationunit set name  = 'BEN-CBD Bengaluru', shortname  = 'BEN-CBD Bengaluru' where organisationunitid = 20508;
update organisationunit set name  = 'BEN-ORS Binnybet', shortname  = 'BEN-ORS Binnybet' where organisationunitid = 20509;
update organisationunit set name  = 'BEN-ORS Hebbal Dasarahalli', shortname  = 'BEN-ORS Hebbal Dasarahalli' where organisationunitid = 20512;
update organisationunit set name  = 'BEN-ORS Rajajinagar', shortname  = 'BEN-ORS Rajajinagar' where organisationunitid = 20513;
update organisationunit set name  = 'BEN-ORS Sriramanahalli', shortname  = 'BEN-ORS Sriramanahalli' where organisationunitid = 20510;
update organisationunit set name  = 'BEN-ORS Srirampura', shortname  = 'BEN-ORS Srirampura' where organisationunitid = 20511;
update organisationunit set name  = 'BEN-RH Palaceguttahalli RHFPC', shortname  = 'BEN-RH Palaceguttahalli RHFPC' where organisationunitid = 20504;
update organisationunit set name  = 'BEN-OA Outside Agencies', shortname  = 'BEN-OA Outside Agencies' where organisationunitid = 24906;
update organisationunit set name  = 'BEN-PMP', shortname  = 'BEN-PMP' where organisationunitid = 24848;
update organisationunit set name  = 'BHO-ASC Associated Clinic Bhopal', shortname  = 'BHO-ASC Associated Clinic Bhopal' where organisationunitid = 375359;
update organisationunit set name  = 'BHO-ORS Arera Colony', shortname  = 'BHO-ORS Arera Colony' where organisationunitid = 20212;
update organisationunit set name  = 'BHO-UH Budhwara UFWC', shortname  = 'BHO-UH Budhwara UFWC' where organisationunitid = 20214;
update organisationunit set name  = 'BHO-UH Govindpura UFWC', shortname  = 'BHO-UH Govindpura UFWC' where organisationunitid = 20213;
update organisationunit set name  = 'BHO-RH Arera Colony RHFPC', shortname  = 'BHO-RH Arera Colony RHFPC' where organisationunitid = 20215;
update organisationunit set name  = 'BHO-CBD Bhopal', shortname  = 'BHO-CBD Bhopal' where organisationunitid = 24677;
update organisationunit set name  = 'BHO-OA Outside Agencies', shortname  = 'BHO-OA Outside Agencies' where organisationunitid = 24934;
update organisationunit set name  = 'BHO-PMP', shortname  = 'BHO-PMP' where organisationunitid = 24865;
update organisationunit set name  = 'BHU-ASC Associated Clinic Bhubaneswar', shortname  = 'BHU-ASC Associated Clinic Bhubaneswar' where organisationunitid = 375368;
update organisationunit set name  = 'BHU-CBD Bhubaneswar', shortname  = 'BHU-CBD Bhubaneswar' where organisationunitid = 24682;
update organisationunit set name  = 'BHU-SAT Andharua', shortname  = 'BHU-SAT Andharua' where organisationunitid = 20219;
update organisationunit set name  = 'BHU-ORS Bhubaneswar', shortname  = 'BHU-ORS Bhubaneswar' where organisationunitid = 20220;
update organisationunit set name  = 'BHU-ORS Sikharchandi', shortname  = 'BHU-ORS Sikharchandi' where organisationunitid = 20218;
update organisationunit set name  = 'BHU-RH Hanspal RHFPC', shortname  = 'BHU-RH Hanspal RHFPC' where organisationunitid = 20206;
update organisationunit set name  = 'BHU-OA Outside Agencies', shortname  = 'BHU-OA Outside Agencies' where organisationunitid = 24935;
update organisationunit set name  = 'BHU-PMP', shortname  = 'BHU-PMP' where organisationunitid = 24864;
update organisationunit set name  = 'BID-ASC Associated Clinic Bidar', shortname  = 'BID-ASC Associated Clinic Bidar' where organisationunitid = 375422;
update organisationunit set name  = 'BID-CBD Bidar', shortname  = 'BID-CBD Bidar' where organisationunitid = 20532;
update organisationunit set name  = 'BID-ORS Bidar', shortname  = 'BID-ORS Bidar' where organisationunitid = 20533;
update organisationunit set name  = 'BID-ORS Jambagi', shortname  = 'BID-ORS Jambagi' where organisationunitid = 20534;
update organisationunit set name  = 'BID-RH Bidar RHFPC', shortname  = 'BID-RH Bidar RHFPC' where organisationunitid = 20535;
update organisationunit set name  = 'BID-OA Outside Agencies', shortname  = 'BID-OA Outside Agencies' where organisationunitid = 24921;
update organisationunit set name  = 'BID-PMP', shortname  = 'BID-PMP' where organisationunitid = 24869;
update organisationunit set name  = 'CHE-ASC Associated Clinic Chennai ', shortname  = 'CHE-ASC Associated Clinic Chennai ' where organisationunitid = 375424;
update organisationunit set name  = 'CHE-CBD Chennai', shortname  = 'CHE-CBD Chennai' where organisationunitid = 24715;
update organisationunit set name  = 'CHE-UH KK Nagar UFWC', shortname  = 'CHE-UH KK Nagar UFWC' where organisationunitid = 20547;
update organisationunit set name  = 'CHE-ORS Thiruverkadu', shortname  = 'CHE-ORS Thiruverkadu' where organisationunitid = 20546;
update organisationunit set name  = 'CHE-RH Vadapalani RHFPC', shortname  = 'CHE-RH Vadapalani RHFPC' where organisationunitid = 20548;
update organisationunit set name  = 'CHE-OA Outside Agencies', shortname  = 'CHE-OA Outside Agencies' where organisationunitid = 24936;
update organisationunit set name  = 'CHE-PMP', shortname  = 'CHE-PMP' where organisationunitid = 24868;
update organisationunit set name  = 'DHA-ASC Associated Clinic Dharwad', shortname  = 'DHA-ASC Associated Clinic Dharwad' where organisationunitid = 375426;
update organisationunit set name  = 'DHA-CBD Dharwad', shortname  = 'DHA-CBD Dharwad' where organisationunitid = 24721;
update organisationunit set name  = 'DHA-ORS Dharwad', shortname  = 'DHA-ORS Dharwad' where organisationunitid = 20553;
update organisationunit set name  = 'DHA-SAT Nigadi', shortname  = 'DHA-SAT Nigadi' where organisationunitid = 20554;
update organisationunit set name  = 'DHA-RH Vikas Nagar RHFPC', shortname  = 'DHA-RH Vikas Nagar RHFPC' where organisationunitid = 20555;
update organisationunit set name  = 'DHA-OA Outside Agencies', shortname  = 'DHA-OA Outside Agencies' where organisationunitid = 24938;
update organisationunit set name  = 'DHA-PMP', shortname  = 'DHA-PMP' where organisationunitid = 24863;
update organisationunit set name  = 'DIN-ASC Associated Clinic Dindigul', shortname  = 'DIN-ASC Associated Clinic Dindigul' where organisationunitid = 375428;
update organisationunit set name  = 'DIN-CBD Dindigul', shortname  = 'DIN-CBD Dindigul' where organisationunitid = 24725;
update organisationunit set name  = 'DIN-ORS Dindigul', shortname  = 'DIN-ORS Dindigul' where organisationunitid = 20560;
update organisationunit set name  = 'DIN-RH Co-operative Nagar RHFPC', shortname  = 'DIN-RH Co-operative Nagar RHFPC' where organisationunitid = 20561;
update organisationunit set name  = 'DIN-OA Outside Agencies', shortname  = 'DIN-OA Outside Agencies' where organisationunitid = 24937;
update organisationunit set name  = 'DIN-PMP', shortname  = 'DIN-PMP' where organisationunitid = 24862;
update organisationunit set name  = 'GOM-ASC Associated Clinic Gomia', shortname  = 'GOM-ASC Associated Clinic Gomia' where organisationunitid = 375430;
update organisationunit set name  = 'GOM-CBD Gomia', shortname  = 'GOM-CBD Gomia' where organisationunitid = 24726;
update organisationunit set name  = 'GOM-ORS Gomia', shortname  = 'GOM-ORS Gomia' where organisationunitid = 20225;
update organisationunit set name  = 'GOM-RH IEL Gomia  RHFPC', shortname  = 'GOM-RH IEL Gomia  RHFPC' where organisationunitid = 20224;
update organisationunit set name  = 'GOM-OA Outside Agencies', shortname  = 'GOM-OA Outside Agencies' where organisationunitid = 24939;
update organisationunit set name  = 'GOM-PMP', shortname  = 'GOM-PMP' where organisationunitid = 24867;
update organisationunit set name  = 'GWA-ASC Associated Clinic Gwalior', shortname  = 'GWA-ASC Associated Clinic Gwalior' where organisationunitid = 375433;
update organisationunit set name  = 'GWA-CBD Gwalior', shortname  = 'GWA-CBD Gwalior' where organisationunitid = 24728;
update organisationunit set name  = 'GWA-UH Kampoo Road UFWC', shortname  = 'GWA-UH Kampoo Road UFWC' where organisationunitid = 20162;
update organisationunit set name  = 'GWA-SAT Khedapati Road-2', shortname  = 'GWA-SAT Khedapati Road-2' where organisationunitid = 20202;
update organisationunit set name  = 'GWA-UH Kherapati Road UFWC', shortname  = 'GWA-UH Kherapati Road UFWC' where organisationunitid = 20160;
update organisationunit set name  = 'GWA-ORS Pinto Park', shortname  = 'GWA-ORS Pinto Park' where organisationunitid = 20161;
update organisationunit set name  = 'GWA-RH Gola Ka Mandir RHFPC', shortname  = 'GWA-RH Gola Ka Mandir RHFPC' where organisationunitid = 20159;
update organisationunit set name  = 'GWA-OA Outside Agencies', shortname  = 'GWA-OA Outside Agencies' where organisationunitid = 24940;
update organisationunit set name  = 'GWA-PMP', shortname  = 'GWA-PMP' where organisationunitid = 24861;
update organisationunit set name  = 'HYD-ASC Associated Clinic Hyderabad', shortname  = 'HYD-ASC Associated Clinic Hyderabad' where organisationunitid = 375435;
update organisationunit set name  = 'HYD-CBD Jinnaram', shortname  = 'HYD-CBD Jinnaram' where organisationunitid = 24733;
update organisationunit set name  = 'HYD-CBD Moosapet', shortname  = 'HYD-CBD Moosapet' where organisationunitid = 24731;
update organisationunit set name  = 'HYD-CBD Panjagutta', shortname  = 'HYD-CBD Panjagutta' where organisationunitid = 20565;
update organisationunit set name  = 'HYD-CBD Rasoolpura', shortname  = 'HYD-CBD Rasoolpura' where organisationunitid = 24732;
update organisationunit set name  = 'HYD-ORS Jinnaram', shortname  = 'HYD-ORS Jinnaram' where organisationunitid = 20566;
update organisationunit set name  = 'HYD-ORS Moosapet', shortname  = 'HYD-ORS Moosapet' where organisationunitid = 20568;
update organisationunit set name  = 'HYD-ORS Rasoolpura', shortname  = 'HYD-ORS Rasoolpura' where organisationunitid = 20567;
update organisationunit set name  = 'HYD-RH Panjagutta RHFPC', shortname  = 'HYD-RH Panjagutta RHFPC' where organisationunitid = 20569;
update organisationunit set name  = 'HYD-OA Outside Agencies', shortname  = 'HYD-OA Outside Agencies' where organisationunitid = 24941;
update organisationunit set name  = 'HYD-PMP', shortname  = 'HYD-PMP' where organisationunitid = 24880;
update organisationunit set name  = 'IND-ASC Associated Clinic Indore', shortname  = 'IND-ASC Associated Clinic Indore' where organisationunitid = 375437;
update organisationunit set name  = 'IND-CBD Indore', shortname  = 'IND-CBD Indore' where organisationunitid = 20440;
update organisationunit set name  = 'IND-ORS Banganga', shortname  = 'IND-ORS Banganga' where organisationunitid = 20229;
update organisationunit set name  = 'IND-RH Chimanbagh RHFPC', shortname  = 'IND-RH Chimanbagh RHFPC' where organisationunitid = 20230;
update organisationunit set name  = 'IND-OA Outside Agencies', shortname  = 'IND-OA Outside Agencies' where organisationunitid = 24942;
update organisationunit set name  = 'IND-PMP', shortname  = 'IND-PMP' where organisationunitid = 24875;
update organisationunit set name  = 'JAB-ASC Associated Clinic Jabalpur ', shortname  = 'JAB-ASC Associated Clinic Jabalpur ' where organisationunitid = 375439;
update organisationunit set name  = 'JAB-CBD Jabalpur', shortname  = 'JAB-CBD Jabalpur' where organisationunitid = 20441;
update organisationunit set name  = 'JAB-UH Bhantallya UFWC', shortname  = 'JAB-UH Bhantallya UFWC' where organisationunitid = 20236;
update organisationunit set name  = 'JAB-ORS Jabalpur Urban', shortname  = 'JAB-ORS Jabalpur Urban' where organisationunitid = 20235;
update organisationunit set name  = 'JAB-UH Madan Mahal UFWC', shortname  = 'JAB-UH Madan Mahal UFWC' where organisationunitid = 20237;
update organisationunit set name  = 'JAB-UH Sihora Rural UFWC', shortname  = 'JAB-UH Sihora Rural UFWC' where organisationunitid = 20238;
update organisationunit set name  = 'JAB-RH Damoh Naka RHFPC', shortname  = 'JAB-RH Damoh Naka RHFPC' where organisationunitid = 20234;
update organisationunit set name  = 'JAB-OA Outside Agencies', shortname  = 'JAB-OA Outside Agencies' where organisationunitid = 24943;
update organisationunit set name  = 'JAB-PMP', shortname  = 'JAB-PMP' where organisationunitid = 24871;
update organisationunit set name  = 'JAI-ASC Associated Clinic Jaipur', shortname  = 'JAI-ASC Associated Clinic Jaipur' where organisationunitid = 375441;
update organisationunit set name  = 'JAI-CBD Jaipur', shortname  = 'JAI-CBD Jaipur' where organisationunitid = 24741;
update organisationunit set name  = 'JAI-ORS Bassi_ORS', shortname  = 'JAI-ORS Bassi_ORS' where organisationunitid = 20244;
update organisationunit set name  = 'JAI-ORS Jaipur', shortname  = 'JAI-ORS Jaipur' where organisationunitid = 20245;
update organisationunit set name  = 'JAI-SAT Pelia Village', shortname  = 'JAI-SAT Pelia Village' where organisationunitid = 20243;
update organisationunit set name  = 'JAI-RH Bassi RHFPC', shortname  = 'JAI-RH Bassi RHFPC' where organisationunitid = 20242;
update organisationunit set name  = 'JAI-OA Outside Agencies', shortname  = 'JAI-OA Outside Agencies' where organisationunitid = 24944;
update organisationunit set name  = 'JAI-PMP', shortname  = 'JAI-PMP' where organisationunitid = 24881;
update organisationunit set name  = 'KAL-ASC Associated Clinic Kalchini', shortname  = 'KAL-ASC Associated Clinic Kalchini' where organisationunitid = 24743;
update organisationunit set name  = 'KAL-CBD Kalchini', shortname  = 'KAL-CBD Kalchini' where organisationunitid = 24745;
update organisationunit set name  = 'KAL-ORS Buxa Duar', shortname  = 'KAL-ORS Buxa Duar' where organisationunitid = 20252;
update organisationunit set name  = 'KAL-SAT Madarihat', shortname  = 'KAL-SAT Madarihat' where organisationunitid = 20250;
update organisationunit set name  = 'KAL-ORS Tea Gardens', shortname  = 'KAL-ORS Tea Gardens' where organisationunitid = 20251;
update organisationunit set name  = 'KAL-RH Kalchini  RHFPC', shortname  = 'KAL-RH Kalchini  RHFPC' where organisationunitid = 20249;
update organisationunit set name  = 'KAL-OA Outside Agencies', shortname  = 'KAL-OA Outside Agencies' where organisationunitid = 24945;
update organisationunit set name  = 'KAL-PMP', shortname  = 'KAL-PMP' where organisationunitid = 24878;
update organisationunit set name  = 'KOL-ASC Associated Clinic Kolkata', shortname  = 'KOL-ASC Associated Clinic Kolkata' where organisationunitid = 272540;
update organisationunit set name  = 'KOL-CBD Kolkata', shortname  = 'KOL-CBD Kolkata' where organisationunitid = 20444;
update organisationunit set name  = 'KOL-SAT Lake Gardens', shortname  = 'KOL-SAT Lake Gardens' where organisationunitid = 20257;
update organisationunit set name  = 'KOL-SAT Rajarhat', shortname  = 'KOL-SAT Rajarhat' where organisationunitid = 20259;
update organisationunit set name  = 'KOL-SAT Tiljala', shortname  = 'KOL-SAT Tiljala' where organisationunitid = 20258;
update organisationunit set name  = 'KOL-RH Christopher Road RHFPC', shortname  = 'KOL-RH Christopher Road RHFPC' where organisationunitid = 20256;
update organisationunit set name  = 'KOL-OA Outside Agencies', shortname  = 'KOL-OA Outside Agencies' where organisationunitid = 24946;
update organisationunit set name  = 'KOL-PMP', shortname  = 'KOL-PMP' where organisationunitid = 24876;
update organisationunit set name  = 'LUC-ASC Associated Clinic Lucknow', shortname  = 'LUC-ASC Associated Clinic Lucknow' where organisationunitid = 375443;
update organisationunit set name  = 'LUC-CBD Lucknow', shortname  = 'LUC-CBD Lucknow' where organisationunitid = 20445;
update organisationunit set name  = 'LUC-ORS Bakshika Talaab', shortname  = 'LUC-ORS Bakshika Talaab' where organisationunitid = 20460;
update organisationunit set name  = 'LUC-UH Cantt. General Hospital UFWC', shortname  = 'LUC-UH Cantt. General Hospital UFWC' where organisationunitid = 20466;
update organisationunit set name  = 'LUC-ORS Lucknow', shortname  = 'LUC-ORS Lucknow' where organisationunitid = 20461;
update organisationunit set name  = 'LUC-UH Turiaganj UFWC', shortname  = 'LUC-UH Turiaganj UFWC' where organisationunitid = 20465;
update organisationunit set name  = 'LUC-SAT Cantt. General Hospital', shortname  = 'LUC-SAT Cantt. General Hospital' where organisationunitid = 20463;
update organisationunit set name  = 'LUC-RH Keshav Nagar RHFPC', shortname  = 'LUC-RH Keshav Nagar RHFPC' where organisationunitid = 20462;
update organisationunit set name  = 'LUC-OA Outside Agencies', shortname  = 'LUC-OA Outside Agencies' where organisationunitid = 24947;
update organisationunit set name  = 'LUC-PMP', shortname  = 'LUC-PMP' where organisationunitid = 24877;
update organisationunit set name  = 'MAD-ASC Associated Clinic Madurai', shortname  = 'MAD-ASC Associated Clinic Madurai' where organisationunitid = 375445;
update organisationunit set name  = 'MAD-CBD Madurai', shortname  = 'MAD-CBD Madurai' where organisationunitid = 20573;
update organisationunit set name  = 'MAD-UH Jaihind Puram UFWC', shortname  = 'MAD-UH Jaihind Puram UFWC' where organisationunitid = 20576;
update organisationunit set name  = 'MAD-ORS Madurai South', shortname  = 'MAD-ORS Madurai South' where organisationunitid = 20574;
update organisationunit set name  = 'MAD-ORS Madurai_CSC', shortname  = 'MAD-ORS Madurai_CSC' where organisationunitid = 20575;
update organisationunit set name  = 'MAD-RH Ellis Nagar RHFPC', shortname  = 'MAD-RH Ellis Nagar RHFPC' where organisationunitid = 20577;
update organisationunit set name  = 'MAD-OA Outside Agencies', shortname  = 'MAD-OA Outside Agencies' where organisationunitid = 24948;
update organisationunit set name  = 'MAD-PMP', shortname  = 'MAD-PMP' where organisationunitid = 24882;
update organisationunit set name  = 'MOH-ASC Associated Clinic Mohali ', shortname  = 'MOH-ASC Associated Clinic Mohali ' where organisationunitid = 375447;
update organisationunit set name  = 'MOH-CBD Mohali', shortname  = 'MOH-CBD Mohali' where organisationunitid = 20446;
update organisationunit set name  = 'MOH-ORS Mohali', shortname  = 'MOH-ORS Mohali' where organisationunitid = 20428;
update organisationunit set name  = 'MOH-OA Outside Agencies', shortname  = 'MOH-OA Outside Agencies' where organisationunitid = 24950;
update organisationunit set name  = 'MOH-PMP', shortname  = 'MOH-PMP' where organisationunitid = 24884;
update organisationunit set name  = 'MUM-ASC Associated Clinic Mumbai', shortname  = 'MUM-ASC Associated Clinic Mumbai' where organisationunitid = 272543;
update organisationunit set name  = 'MUM-CBD AWHC -Tilak Nagar', shortname  = 'MUM-CBD AWHC -Tilak Nagar' where organisationunitid = 14455;
update organisationunit set name  = 'MUM-SAT Dongari', shortname  = 'MUM-SAT Dongari' where organisationunitid = 13046;
update organisationunit set name  = 'MUM-ORS Mumbai', shortname  = 'MUM-ORS Mumbai' where organisationunitid = 20265;
update organisationunit set name  = 'MUM-ORS KSK Colaba', shortname  = 'MUM-ORS KSK Colaba' where organisationunitid = 20266;
update organisationunit set name  = 'MUM-ORS Lotus Colony Tata pr', shortname  = 'MUM-ORS Lotus Colony Tata pr' where organisationunitid = 20272;
update organisationunit set name  = 'MUM-ORS Shivaji Nagar', shortname  = 'MUM-ORS Shivaji Nagar' where organisationunitid = 13045;
update organisationunit set name  = 'MUM-ORS Vasi Nakka', shortname  = 'MUM-ORS Vasi Nakka' where organisationunitid = 20273;
update organisationunit set name  = 'MUM-RH AWHC RHFPC', shortname  = 'MUM-RH AWHC RHFPC' where organisationunitid = 13040;
update organisationunit set name  = 'MUM-RH KSK RHFPC', shortname  = 'MUM-RH KSK RHFPC' where organisationunitid = 13043;
update organisationunit set name  = 'MUM-OA Outside Agencies', shortname  = 'MUM-OA Outside Agencies' where organisationunitid = 24969;
update organisationunit set name  = 'MUM-PMP', shortname  = 'MUM-PMP' where organisationunitid = 24885;
update organisationunit set name  = 'MUR-ASC Associated Clinic Murhu', shortname  = 'MUR-ASC Associated Clinic Murhu' where organisationunitid = 375449;
update organisationunit set name  = 'MUR-CBD Khunti Sadar', shortname  = 'MUR-CBD Khunti Sadar' where organisationunitid = 24758;
update organisationunit set name  = 'MUR-ORS Khunti Sadar', shortname  = 'MUR-ORS Khunti Sadar' where organisationunitid = 20277;
update organisationunit set name  = 'MUR-ORS Murhu', shortname  = 'MUR-ORS Murhu' where organisationunitid = 20278;
update organisationunit set name  = 'MUR-RH Khunti RHFPC', shortname  = 'MUR-RH Khunti RHFPC' where organisationunitid = 20279;
update organisationunit set name  = 'MUR-OA Outside Agencies', shortname  = 'MUR-OA Outside Agencies' where organisationunitid = 24952;
update organisationunit set name  = 'MUR-PMP', shortname  = 'MUR-PMP' where organisationunitid = 24886;
update organisationunit set name  = 'MYS-ASC Associated Clinic Mysuru', shortname  = 'MYS-ASC Associated Clinic Mysuru' where organisationunitid = 375451;
update organisationunit set name  = 'MYS-CBD Naidunagar', shortname  = 'MYS-CBD Naidunagar' where organisationunitid = 20448;
update organisationunit set name  = 'MYS-RH Mysuru RHFPC', shortname  = 'MYS-RH Mysuru RHFPC' where organisationunitid = 20289;
update organisationunit set name  = 'MYS-OA Outside Agencies', shortname  = 'MYS-OA Outside Agencies' where organisationunitid = 24970;
update organisationunit set name  = 'MYS-PMP', shortname  = 'MYS-PMP' where organisationunitid = 24887;
update organisationunit set name  = 'NAG-ASC Associated Clinic Nagaland', shortname  = 'NAG-ASC Associated Clinic Nagaland' where organisationunitid = 375453;
update organisationunit set name  = 'NAG-CBD Daklane', shortname  = 'NAG-CBD Daklane' where organisationunitid = 20449;
update organisationunit set name  = 'NAG-ORS Kohima', shortname  = 'NAG-ORS Kohima' where organisationunitid = 20285;
update organisationunit set name  = 'NAG-ORS Upper PWD Colony', shortname  = 'NAG-ORS Upper PWD Colony' where organisationunitid = 20284;
update organisationunit set name  = 'NAG-RH Nagaland RHFPC', shortname  = 'NAG-RH Nagaland RHFPC' where organisationunitid = 20283;
update organisationunit set name  = 'NAG-OA Outside Agencies', shortname  = 'NAG-OA Outside Agencies' where organisationunitid = 24953;
update organisationunit set name  = 'NAG-PMP', shortname  = 'NAG-PMP' where organisationunitid = 24888;
update organisationunit set name  = 'NEW-ASC Associated Clinic New Delhi', shortname  = 'NEW-ASC Associated Clinic New Delhi' where organisationunitid = 375455;
update organisationunit set name  = 'NEW-CBD R.K.Puram', shortname  = 'NEW-CBD R.K.Puram' where organisationunitid = 24762;
update organisationunit set name  = 'NEW-ORS R.K.Puram', shortname  = 'NEW-ORS R.K.Puram' where organisationunitid = 14604;
update organisationunit set name  = 'NEW-RH R.K.Puram RHFPC', shortname  = 'NEW-RH R.K.Puram RHFPC' where organisationunitid = 14603;
update organisationunit set name  = 'NEW-OA Outside Agencies', shortname  = 'NEW-OA Outside Agencies' where organisationunitid = 24954;
update organisationunit set name  = 'NEW-PMP', shortname  = 'NEW-PMP' where organisationunitid = 24873;
update organisationunit set name  = 'NIL-ASC Associated Clinic', shortname  = 'NIL-ASC Associated Clinic' where organisationunitid = 219038;
update organisationunit set name  = 'NIL-CBD Nilgiris', shortname  = 'NIL-CBD Nilgiris' where organisationunitid = 24763;
update organisationunit set name  = 'NIL-ORS Nilgiris', shortname  = 'NIL-ORS Nilgiris' where organisationunitid = 20295;
update organisationunit set name  = 'NIL-RH Coonoor RHFPC', shortname  = 'NIL-RH Coonoor RHFPC' where organisationunitid = 20294;
update organisationunit set name  = 'NIL-OA Outside Agencies', shortname  = 'NIL-OA Outside Agencies' where organisationunitid = 24956;
update organisationunit set name  = 'NIL-PMP', shortname  = 'NIL-PMP' where organisationunitid = 24879;
update organisationunit set name  = 'NOR-ASC Associated Clinic North Kanara', shortname  = 'NOR-ASC Associated Clinic North Kanara' where organisationunitid = 375460;
update organisationunit set name  = 'NOR-CBD Kumta', shortname  = 'NOR-CBD Kumta' where organisationunitid = 24766;
update organisationunit set name  = 'NOR-SAT Kemani', shortname  = 'NOR-SAT Kemani' where organisationunitid = 20301;
update organisationunit set name  = 'NOR-SAT Keni', shortname  = 'NOR-SAT Keni' where organisationunitid = 20302;
update organisationunit set name  = 'NOR-ORS Kumta', shortname  = 'NOR-ORS Kumta' where organisationunitid = 20303;
update organisationunit set name  = 'NOR-UH Kumta UFWC', shortname  = 'NOR-UH Kumta UFWC' where organisationunitid = 20304;
update organisationunit set name  = 'NOR-RH Kumta RHFPC', shortname  = 'NOR-RH Kumta RHFPC' where organisationunitid = 20300;
update organisationunit set name  = 'NOR-OA Outside Agencies', shortname  = 'NOR-OA Outside Agencies' where organisationunitid = 24971;
update organisationunit set name  = 'NOR-PMP', shortname  = 'NOR-PMP' where organisationunitid = 24889;
update organisationunit set name  = 'PAN-OA Outside Agencies', shortname  = 'PAN-OA Outside Agencies' where organisationunitid = 24957;
update organisationunit set name  = 'PAN-ASC Associated Clinic Panchkula', shortname  = 'PAN-ASC Associated Clinic Panchkula' where organisationunitid = 375461;
update organisationunit set name  = 'PAN-CBD Panchkula', shortname  = 'PAN-CBD Panchkula' where organisationunitid = 24768;
update organisationunit set name  = 'PAN-UH Ambala Cantt_UFWC', shortname  = 'PAN-UH Ambala Cantt_UFWC' where organisationunitid = 20311;
update organisationunit set name  = 'PAN-UH Kalka UFWC', shortname  = 'PAN-UH Kalka UFWC' where organisationunitid = 20312;
update organisationunit set name  = 'PAN-ORS Panchkula', shortname  = 'PAN-ORS Panchkula' where organisationunitid = 20310;
update organisationunit set name  = 'PAN-RH Haripur RHFPC', shortname  = 'PAN-RH Haripur RHFPC' where organisationunitid = 20309;
update organisationunit set name  = 'PAN-PMP', shortname  = 'PAN-PMP' where organisationunitid = 24883;
update organisationunit set name  = 'PAT-OA Outside Agencies', shortname  = 'PAT-OA Outside Agencies' where organisationunitid = 24958;
update organisationunit set name  = 'PAT-CBD Patna', shortname  = 'PAT-CBD Patna' where organisationunitid = 20454;
update organisationunit set name  = 'PAT-ORS Phulwari Sharif', shortname  = 'PAT-ORS Phulwari Sharif' where organisationunitid = 20318;
update organisationunit set name  = 'PAT-PMP', shortname  = 'PAT-PMP' where organisationunitid = 24890;
update organisationunit set name  = 'PUN-OA Outside Agencies', shortname  = 'PUN-OA Outside Agencies' where organisationunitid = 24959;
update organisationunit set name  = 'PUN-PMP', shortname  = 'PUN-PMP' where organisationunitid = 24891;
update organisationunit set name  = 'PUN-ASC Associated Clinic Pune', shortname  = 'PUN-ASC Associated Clinic Pune' where organisationunitid = 375463;
update organisationunit set name  = 'PUN-CBD Shivaji Nagar', shortname  = 'PUN-CBD Shivaji Nagar' where organisationunitid = 14532;
update organisationunit set name  = 'PUN-ORS Ambedkar Nagar', shortname  = 'PUN-ORS Ambedkar Nagar' where organisationunitid = 20325;
update organisationunit set name  = 'PUN-ORS Dandekar Bridge', shortname  = 'PUN-ORS Dandekar Bridge' where organisationunitid = 14609;
update organisationunit set name  = 'PUN-ORS Gokhale Nagar', shortname  = 'PUN-ORS Gokhale Nagar' where organisationunitid = 14610;
update organisationunit set name  = 'PUN-ORS Gultekdi', shortname  = 'PUN-ORS Gultekdi' where organisationunitid = 20324;
update organisationunit set name  = 'PUN-ORS Kothrud', shortname  = 'PUN-ORS Kothrud' where organisationunitid = 20322;
update organisationunit set name  = 'PUN-ORS Mulshi', shortname  = 'PUN-ORS Mulshi' where organisationunitid = 14611;
update organisationunit set name  = 'PUN-SAT Paud', shortname  = 'PUN-SAT Paud' where organisationunitid = 20319;
update organisationunit set name  = 'PUN-SAT Pawan Nagar', shortname  = 'PUN-SAT Pawan Nagar' where organisationunitid = 20320;
update organisationunit set name  = 'PUN-SAT Rajiv Gandhi Nagar', shortname  = 'PUN-SAT Rajiv Gandhi Nagar' where organisationunitid = 20321;
update organisationunit set name  = 'PUN-ORS Shivajinagar', shortname  = 'PUN-ORS Shivajinagar' where organisationunitid = 14607;
update organisationunit set name  = 'PUN-ORS Upper Indira Nagar', shortname  = 'PUN-ORS Upper Indira Nagar' where organisationunitid = 20323;
update organisationunit set name  = 'PUN-ORS Wadarwadi', shortname  = 'PUN-ORS Wadarwadi' where organisationunitid = 14608;
update organisationunit set name  = 'PUN-RH Chandni Chowk RHFPC', shortname  = 'PUN-RH Chandni Chowk RHFPC' where organisationunitid = 14606;
update organisationunit set name  = 'PUN-RH Shivajinagar RHFPC ', shortname  = 'PUN-RH Shivajinagar RHFPC ' where organisationunitid = 14605;
update organisationunit set name  = 'RAI-OA Outside Agencies', shortname  = 'RAI-OA Outside Agencies' where organisationunitid = 24960;
update organisationunit set name  = 'RAI-PMP', shortname  = 'RAI-PMP' where organisationunitid = 24892;
update organisationunit set name  = 'RAI-ASC Associated Clinic Raichur', shortname  = 'RAI-ASC Associated Clinic Raichur' where organisationunitid = 375465;
update organisationunit set name  = 'RAI-CBD Raichur', shortname  = 'RAI-CBD Raichur' where organisationunitid = 24784;
update organisationunit set name  = 'RAI-ORS Raichur', shortname  = 'RAI-ORS Raichur' where organisationunitid = 20331;
update organisationunit set name  = 'RAI-RH Goshala Road RHFPC', shortname  = 'RAI-RH Goshala Road RHFPC' where organisationunitid = 20330;
update organisationunit set name  = 'RAJ-OA Outside Agencies', shortname  = 'RAJ-OA Outside Agencies' where organisationunitid = 24961;
update organisationunit set name  = 'RAJ-PMP', shortname  = 'RAJ-PMP' where organisationunitid = 24893;
update organisationunit set name  = 'RAJ-ASC Associated Clinic Rajkot', shortname  = 'RAJ-ASC Associated Clinic Rajkot' where organisationunitid = 375467;
update organisationunit set name  = 'RAJ-CBD Rajkot', shortname  = 'RAJ-CBD Rajkot' where organisationunitid = 20456;
update organisationunit set name  = 'RAJ-UH Rajkot UFWC', shortname  = 'RAJ-UH Rajkot UFWC' where organisationunitid = 20335;
update organisationunit set name  = 'RAJ-ORS Rajkot', shortname  = 'RAJ-ORS Rajkot' where organisationunitid = 20334;
update organisationunit set name  = 'SAG-OA Outside Agencies', shortname  = 'SAG-OA Outside Agencies' where organisationunitid = 24962;
update organisationunit set name  = 'SAG-PMP', shortname  = 'SAG-PMP' where organisationunitid = 24894;
update organisationunit set name  = 'SAG-ASC Associated Clinic Sagar', shortname  = 'SAG-ASC Associated Clinic Sagar' where organisationunitid = 375469;
update organisationunit set name  = 'SAG-CBD Sagar', shortname  = 'SAG-CBD Sagar' where organisationunitid = 20457;
update organisationunit set name  = 'SAG-SAT Sagar', shortname  = 'SAG-SAT Sagar' where organisationunitid = 20338;
update organisationunit set name  = 'SHI-OA Outside Agencies', shortname  = 'SHI-OA Outside Agencies' where organisationunitid = 24963;
update organisationunit set name  = 'SHI-PMP', shortname  = 'SHI-PMP' where organisationunitid = 24851;
update organisationunit set name  = 'SHI-ASC Associated Clinic Shivamogga', shortname  = 'SHI-ASC Associated Clinic Shivamogga' where organisationunitid = 375471;
update organisationunit set name  = 'SHI-CBD Shimoga', shortname  = 'SHI-CBD Shimoga' where organisationunitid = 24787;
update organisationunit set name  = 'SHI-UH Kote Road UFWC', shortname  = 'SHI-UH Kote Road UFWC' where organisationunitid = 20343;
update organisationunit set name  = 'SHI-ORS Shimoga', shortname  = 'SHI-ORS Shimoga' where organisationunitid = 20344;
update organisationunit set name  = 'SHI-RH Malleshwara Nagar RHFPC', shortname  = 'SHI-RH Malleshwara Nagar RHFPC' where organisationunitid = 20348;
update organisationunit set name  = 'SIN-OA Outside Agencies', shortname  = 'SIN-OA Outside Agencies' where organisationunitid = 24964;
update organisationunit set name  = 'SIN-PMP', shortname  = 'SIN-PMP' where organisationunitid = 24854;
update organisationunit set name  = 'SIN-ASC Associated Clinic Singhbhum', shortname  = 'SIN-ASC Associated Clinic Singhbhum' where organisationunitid = 375473;
update organisationunit set name  = 'SIN-CBD Gamharia', shortname  = 'SIN-CBD Gamharia' where organisationunitid = 24788;
update organisationunit set name  = 'SIN-CBD West Singhbhum', shortname  = 'SIN-CBD West Singhbhum' where organisationunitid = 24789;
update organisationunit set name  = 'SIN-ORS Gamharia', shortname  = 'SIN-ORS Gamharia' where organisationunitid = 20352;
update organisationunit set name  = 'SIN-ORS West Singhbhum', shortname  = 'SIN-ORS West Singhbhum' where organisationunitid = 20353;
update organisationunit set name  = 'SIN-RH Gamharia RHFPC', shortname  = 'SIN-RH Gamharia RHFPC' where organisationunitid = 20354;
update organisationunit set name  = 'SOL-OA Outside Agencies', shortname  = 'SOL-OA Outside Agencies' where organisationunitid = 24965;
update organisationunit set name  = 'SOL-PMP', shortname  = 'SOL-PMP' where organisationunitid = 24852;
update organisationunit set name  = 'SOL-ASC Associated Clinic Solapur', shortname  = 'SOL-ASC Associated Clinic Solapur' where organisationunitid = 375475;
update organisationunit set name  = 'SOL-CBD Solapur', shortname  = 'SOL-CBD Solapur' where organisationunitid = 14583;
update organisationunit set name  = 'SOL-ORS Old Vidi Gharkul', shortname  = 'SOL-ORS Old Vidi Gharkul' where organisationunitid = 14713;
update organisationunit set name  = 'SOL-ORS Bhavani Peth', shortname  = 'SOL-ORS Bhavani Peth' where organisationunitid = 14614;
update organisationunit set name  = 'SOL-RH Sakhar Peth RHFPC', shortname  = 'SOL-RH Sakhar Peth RHFPC' where organisationunitid = 14612;
update organisationunit set name  = 'SOU-OA Outside Agencies', shortname  = 'SOU-OA Outside Agencies' where organisationunitid = 24966;
update organisationunit set name  = 'SOU-PMP', shortname  = 'SOU-PMP' where organisationunitid = 24855;
update organisationunit set name  = 'SOU-ASC Associated Clinic South Kanara', shortname  = 'SOU-ASC Associated Clinic South Kanara' where organisationunitid = 375477;
update organisationunit set name  = 'SOU-CBD Kukkikatte', shortname  = 'SOU-CBD Kukkikatte' where organisationunitid = 20362;
update organisationunit set name  = 'SOU-ORS Indira Nagar', shortname  = 'SOU-ORS Indira Nagar' where organisationunitid = 20364;
update organisationunit set name  = 'SOU-UH Kukkikatte UFWC', shortname  = 'SOU-UH Kukkikatte UFWC' where organisationunitid = 20363;
update organisationunit set name  = 'SOU-ORS Mission Compound ', shortname  = 'SOU-ORS Mission Compound ' where organisationunitid = 20368;
update organisationunit set name  = 'SRI-OA Outside Agencies', shortname  = 'SRI-OA Outside Agencies' where organisationunitid = 24967;
update organisationunit set name  = 'SRI-PMP', shortname  = 'SRI-PMP' where organisationunitid = 24853;
update organisationunit set name  = 'SRI-ASC Associated Clinic Srinagar', shortname  = 'SRI-ASC Associated Clinic Srinagar' where organisationunitid = 375479;
update organisationunit set name  = 'SRI-CBD Budgam', shortname  = 'SRI-CBD Budgam' where organisationunitid = 20434;
update organisationunit set name  = 'SRI-ORS Budgam', shortname  = 'SRI-ORS Budgam' where organisationunitid = 20371;
update organisationunit set name  = 'THA-OA Outside Agencies', shortname  = 'THA-OA Outside Agencies' where organisationunitid = 376662;
update organisationunit set name  = 'THA-PMP', shortname  = 'THA-PMP' where organisationunitid = 376663;
update organisationunit set name  = 'THA-ASC Associated Clinic Thane', shortname  = 'THA-ASC Associated Clinic Thane' where organisationunitid = 376793;
update organisationunit set name  = 'THA-CBD Thane', shortname  = 'THA-CBD Thane' where organisationunitid = 376794;
update organisationunit set name  = 'THA-ORS Azami Nagar Migrant', shortname  = 'THA-ORS Azami Nagar Migrant' where organisationunitid = 13050;
update organisationunit set name  = 'THA-ORS Thane', shortname  = 'THA-ORS Thane' where organisationunitid = 20270;
update organisationunit set name  = 'THA-SAT Ganeshpuri', shortname  = 'THA-SAT Ganeshpuri' where organisationunitid = 13047;
update organisationunit set name  = 'THA-ORS Hanuman Tekadi-TI FSW', shortname  = 'THA-ORS Hanuman Tekadi-TI FSW' where organisationunitid = 20271;
update organisationunit set name  = 'THA-ORS Kalyan-TI FSW', shortname  = 'THA-ORS Kalyan-TI FSW' where organisationunitid = 14258;
update organisationunit set name  = 'THA-ORS Padma Nagar-Ti Migrant', shortname  = 'THA-ORS Padma Nagar-Ti Migrant' where organisationunitid = 13049;
update organisationunit set name  = 'THA-ORS PSK-Nehru Nagar', shortname  = 'THA-ORS PSK-Nehru Nagar' where organisationunitid = 20267;
update organisationunit set name  = 'THA-ORS Taware Compound-TI Migrant', shortname  = 'THA-ORS Taware Compound-TI Migrant' where organisationunitid = 20268;
update organisationunit set name  = 'THA-RH KNAK RHFPC', shortname  = 'THA-RH KNAK RHFPC' where organisationunitid = 13041;
update organisationunit set name  = 'THA-RH PSK RHFPC', shortname  = 'THA-RH PSK RHFPC' where organisationunitid = 13042;
update organisationunit set name  = 'TRI-OA Outside Agencies', shortname  = 'TRI-OA Outside Agencies' where organisationunitid = 24968;
update organisationunit set name  = 'TRI-PMP', shortname  = 'TRI-PMP' where organisationunitid = 24844;
update organisationunit set name  = 'TRI-ASC Associated Clinic Trivandrum', shortname  = 'TRI-ASC Associated Clinic Trivandrum' where organisationunitid = 375481;
update organisationunit set name  = 'TRI-CBD Trivandrum', shortname  = 'TRI-CBD Trivandrum' where organisationunitid = 20433;
update organisationunit set name  = 'TRI-ORS Corporation Area', shortname  = 'TRI-ORS Corporation Area' where organisationunitid = 20378;
update organisationunit set name  = 'VIJ-OA Outside Agencies', shortname  = 'VIJ-OA Outside Agencies' where organisationunitid = 24927;
update organisationunit set name  = 'VIJ-PMP', shortname  = 'VIJ-PMP' where organisationunitid = 24866;
update organisationunit set name  = 'VIJ-ASC Associated Clinic Vijayapur', shortname  = 'VIJ-ASC Associated Clinic Vijayapur' where organisationunitid = 375673;
update organisationunit set name  = 'VIJ-CBD Vijayapur', shortname  = 'VIJ-CBD Vijayapur' where organisationunitid = 24714;
update organisationunit set name  = 'VIJ-ORS Vajra Hanuman Nagar', shortname  = 'VIJ-ORS Vajra Hanuman Nagar' where organisationunitid = 20540;
update organisationunit set name  = 'VIJ-RH Vijayapur RHFPC', shortname  = 'VIJ-RH Vijayapur RHFPC' where organisationunitid = 20541;
update organisationunit set name  = 'YAM-OA Outside Agencies', shortname  = 'YAM-OA Outside Agencies' where organisationunitid = 24897;
update organisationunit set name  = 'YAM-PMP', shortname  = 'YAM-PMP' where organisationunitid = 24840;
update organisationunit set name  = 'YAM-ASC Associated Clinic Yamunanagar', shortname  = 'YAM-ASC Associated Clinic Yamunanagar' where organisationunitid = 24792;
update organisationunit set name  = 'YAM-CBD Yamunanagar', shortname  = 'YAM-CBD Yamunanagar' where organisationunitid = 24793;
update organisationunit set name  = 'YAM-ORS Yamunanagar', shortname  = 'YAM-ORS Yamunanagar' where organisationunitid = 20386;
update organisationunit set name  = 'YAM-RH Yamunanagar RHFPC', shortname  = 'YAM-RH Yamunanagar RHFPC' where organisationunitid = 20385;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14270;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14271;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14410;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 20526;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 20521;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24667;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24670;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24671;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24668;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24669;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 20467;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24679;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24678;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 20217;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 20216;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24681;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 20437;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24680;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24713;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24689;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24719;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 20545;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24720;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 20552;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 20559;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 20438;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 20439;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24729;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24727;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24730;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24734;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24736;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24735;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24737;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24738;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24740;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 20442;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24739;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24747;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24746;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 20443;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24744;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24748;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24750;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24749;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24751;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24241;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24754;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24752;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24753;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24755;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24757;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24756;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14464;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14460;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14458;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14466;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14457;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14459;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14468;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14467;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14454;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14452;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14469;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14462;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14465;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14453;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14456;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14463;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14470;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14461;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 20447;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24759;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24761;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24760;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 20450;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 20451;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24764;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24765;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 20452;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24767;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24769;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 20453;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24770;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24774;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 20317;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14538;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14535;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14528;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14534;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14537;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14533;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14529;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14530;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14531;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14527;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14536;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14539;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 20455;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24785;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24786;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 20458;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 20459;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14584;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14582;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14581;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14615;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 20359;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 20355;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 14613;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24790;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24791;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 20539;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 24794;
update organisationunit set closeddate  = '2018-09-06' where organisationunitid = 20432;
end;
