begin;


update dataelement set formname  = 'Cause of death سبب الوفاة' where dataelementid = 8799 and uid = 'omNaP8JjJ6W';
update dataelement set formname  = 'Needle size used حجم ابرة التوصيل المستخدمة' where dataelementid = 8806 and uid = 'jiljIqW5Ltn';
update dataelement set formname  = 'Filter type used نوع  الفلتر' where dataelementid = 8807 and uid = 'XvX8tZwuiZD';
update dataelement set formname  = 'Filter size used حجم الفلتر' where dataelementid = 8808 and uid = 'LE2DXwPzhAA';
update dataelement set formname  = 'Instrument type نوع الجهاز' where dataelementid = 8809 and uid = 'DnBeP1QLE3c';
update dataelement set formname  = 'Medication name I اسم الدواء I' where dataelementid = 8810 and uid = 'fGVJbr2ClQ8';
update dataelement set formname  = 'Medication name II اسم الدواء II' where dataelementid = 8811 and uid = 'WNeG4q3Iv6R';
update dataelement set formname  = 'Medication name III اسم الدواء III' where dataelementid = 8812 and uid = 'ks4VdYNjq7a';
update dataelement set formname  = 'Medication name IV اسم الدواء IV' where dataelementid = 8813 and uid = 'qRMcdYUA08l';
update dataelement set formname  = 'Medication name V اسم الدواء V' where dataelementid = 8814 and uid = 'ClOFRO1g7rM';
update dataelement set formname  = 'Medication name VI اسم الدواء VI' where dataelementid = 8815 and uid = 'tsV5MACCvj2';
update dataelement set formname  = 'Medication name VII اسم الدواء VII' where dataelementid = 8816 and uid = 'jIZd9Esxo2R';
update dataelement set formname  = 'Medication name VIII اسم الدواء VIII' where dataelementid = 8817 and uid = 'PoHs3JJaNph';
update dataelement set formname  = 'Medication name IX اسم الدواء IX' where dataelementid = 8818 and uid = 'WPkndEHFbNc';
update dataelement set formname  = 'Medication name X اسم الدواء X' where dataelementid = 8819 and uid = 'GYYrciD3NtG';
update dataelement set formname  = 'Medication dosage I جرعة الدواء I' where dataelementid = 8820 and uid = 'Ki1qDmXTmo4';
update dataelement set formname  = 'Medication dosage II جرعة الدواء II' where dataelementid = 8821 and uid = 'k4IiZzpBZK9';
update dataelement set formname  = 'Medication dosage III جرعة الدواء III' where dataelementid = 8822 and uid = 'oGbn8mSDozq';
update dataelement set formname  = 'Medication dosage IV جرعة الدواء IV' where dataelementid = 8823 and uid = 'Jy33cdIMf2w';
update dataelement set formname  = 'Medication dosage V جرعة الدواء V' where dataelementid = 8824 and uid = 'j4clJp3IsT2';
update dataelement set formname  = 'Medication dosage VI جرعة الدواء VI' where dataelementid = 8825 and uid = 'OEp5MEB5i7x';
update dataelement set formname  = 'Renal failure type نوع الفشل الكلوي' where dataelementid = 8800 and uid = 'QgVClunvp0m';
update dataelement set formname  = 'Vascular access for dialysis type عن طريق التوصيلة الدموية' where dataelementid = 8804 and uid = 'QuRCA6rDYDu';
update dataelement set formname  = 'Dialysis type نوع الغسيل' where dataelementid = 8803 and uid = 'xOoxSfueUrs';
update dataelement set formname  = 'Viral screening result الفحص الفيروسي ' where dataelementid = 8802 and uid = 'BOB8CvA1Ysn';
update dataelement set formname  = 'Medication dosage VII جرعة الدواء VII' where dataelementid = 8826 and uid = 'v7aKeYRoRIl';
update dataelement set formname  = 'Medication dosage VIII جرعة الدواء VIII' where dataelementid = 8827 and uid = 'Ze4g5JJhZvq';
update dataelement set formname  = 'Medication dosage IX جرعة الدواء IX' where dataelementid = 8828 and uid = 'KNwFxUhKml1';
update dataelement set formname  = 'Medication dosage X جرعة الدواء X' where dataelementid = 8829 and uid = 'xgqNYT9sJJx';
update dataelement set formname  = 'Testing method used طريقة الفحص المستخدم' where dataelementid = 9093 and uid = 'ky1gJ7M3PIn';
update dataelement set formname  = 'Previous test result  نتيجة الفحص السابق' where dataelementid = 9095 and uid = 'cEmxzkS0iuO';
update dataelement set formname  = 'Previous test result date تاريخ نتيجة الفحص السابق' where dataelementid = 9096 and uid = 'GiafobeSDYB';
update dataelement set formname  = 'Patient informed ' where dataelementid = 9098 and uid = 'ojf2eTb3HiN';
update dataelement set formname  = 'Patient name اسم المريض' where dataelementid = 9099 and uid = 'I6YGCtch4IM';
update dataelement set formname  = 'Age at death العمر عند الوفاة' where dataelementid = 9100 and uid = 'Jsx6oIt5X5O';
update dataelement set formname  = 'Time of death وقت الوفاة' where dataelementid = 9101 and uid = 'NI83gKKA7Nm';
update dataelement set formname  = 'Place of death مكان الوفاة' where dataelementid = 9102 and uid = 'Zl5R1hMmVlZ';
update dataelement set formname  = 'Maternal death event  وفيات امهات' where dataelementid = 9103 and uid = 'xpRRhsUNeNE';
update dataelement set formname  = 'Delivery/Termination of pregnancy date تاريخ الولادة/ تالريخ انهاء الحمل' where dataelementid = 9104 and uid = 'xPNYxOSUGg5';
update dataelement set formname  = 'Delivery outcome ناتج الولادة' where dataelementid = 9105 and uid = 'OG0DFdUGdPt';
update dataelement set formname  = 'Nationality اسم المرض المشتبه به' where dataelementid = 9108 and uid = 'dr3eAhOCKyv';
update dataelement set formname  = 'Age العمر' where dataelementid = 9110 and uid = 'hDPezniOnwQ';
update dataelement set formname  = 'Gender الجنسية' where dataelementid = 9109 and uid = 'Y3PTpRBCn4E';
update dataelement set formname  = 'Occupation الجنس' where dataelementid = 9111 and uid = 'tguM9QIXVqL';
update dataelement set formname  = 'Current address العنوان الحالي' where dataelementid = 9112 and uid = 'zSRqN3SywCC';
update dataelement set formname  = 'Phone number رقم الهاتف' where dataelementid = 9113 and uid = 'lGAcQRx7AMn';
update dataelement set formname  = 'Patient displaced هل المريض نازح' where dataelementid = 9114 and uid = 'Yk3pblZXPYm';
update dataelement set formname  = 'Displaced location  النازح من اي بلدية' where dataelementid = 9115 and uid = 'sUatMulVkvt';
update dataelement set formname  = 'Medication frequency II عدد مرات المداواة (إعطاء الدواء) II' where dataelementid = 8831 and uid = 'M2Kr0nDuY4j';
update dataelement set formname  = 'Medication frequency III عدد مرات المداواة (إعطاء الدواء) III' where dataelementid = 8832 and uid = 'cMiRaXuWUSk';
update dataelement set formname  = 'Medication frequency IV عدد مرات المداواة (إعطاء الدواء) IV' where dataelementid = 8833 and uid = 'eqDuzhAEkJS';
update dataelement set formname  = 'Medication frequency IX عدد مرات المداواة (إعطاء الدواء) V' where dataelementid = 8838 and uid = 'XHF6DOG5Beh';
update dataelement set formname  = 'Medication frequency V عدد مرات المداواة (إعطاء الدواء) VI' where dataelementid = 8834 and uid = 'GyHjzJzO1Qd';
update dataelement set formname  = 'Medication frequency VI عدد مرات المداواة (إعطاء الدواء) VII' where dataelementid = 8835 and uid = 'EFS5EDVrDuU';
update dataelement set formname  = 'Medication frequency VII عدد مرات المداواة (إعطاء الدواء) VIII' where dataelementid = 8836 and uid = 'VWHjrIZhWIC';
update dataelement set formname  = 'Medication frequency VIII عدد مرات المداواة (إعطاء الدواء) IX' where dataelementid = 8837 and uid = 'sW2veqU4ibN';
update dataelement set formname  = 'Medication frequency X عدد مرات المداواة (إعطاء الدواء) X' where dataelementid = 8839 and uid = 'JHZNiXuMPPL';
update dataelement set formname  = 'Cause of death سبب الوفاة' where dataelementid = 9106 and uid = 'pW6VyUlLPZO';
update dataelement set formname  = 'Test result نتيجة الفحص-تفاصيل الفحص' where dataelementid = 9094 and uid = 'rlKGKK49Sfn';
update dataelement set formname  = 'Previous HIV test result date تاريخ نتيجة فحص الايدز السابق' where dataelementid = 9097 and uid = 'lFryR4uzqFN';
update dataelement set formname  = 'Suspected disease الحالة التطعيمية' where dataelementid = 9107 and uid = 'sQzN6pAg2rP';
update dataelement set formname  = 'Immunization status تاريخ اخر جرعة تطعيم' where dataelementid = 9116 and uid = 'EvigI3drjEn';
update dataelement set formname  = 'Last immunisation dose date تاريخ التشخيص' where dataelementid = 9117 and uid = 'OjYIdFL9Fu9';
update dataelement set formname  = 'Diagnosis date  تاريخ ظهور الاعراض' where dataelementid = 9118 and uid = 'zZtKIGGa3cR';
update dataelement set formname  = 'Symptoms onset date  نتيجة المرض' where dataelementid = 9119 and uid = 'p18GkUdjx1v';
update dataelement set formname  = 'Patient outcome مكات الإحالة' where dataelementid = 9120 and uid = 'rT8JrXGnCTV';
update dataelement set formname  = 'Infant name اسم المولود' where dataelementid = 9122 and uid = 'xNvROquvBYr';
update dataelement set formname  = 'Birth status حالة المولود' where dataelementid = 9123 and uid = 'NqsKU5hHRYn';
update dataelement set formname  = 'Delivery mode نوع الولادة' where dataelementid = 9124 and uid = 'z5xj5NUIf0V';
update dataelement set formname  = 'Date of birth تاريخ الولادة' where dataelementid = 9125 and uid = 'CAdH9RM7KL5';
update dataelement set formname  = 'Time of birth وقت الولادة' where dataelementid = 9126 and uid = 'L8OOQEZ0xwk';
update dataelement set formname  = 'Place of birth مكان الولادة' where dataelementid = 9127 and uid = 'eKLd93yBj5m';
update dataelement set formname  = 'Multiple deliveries ولادة متعددة' where dataelementid = 9128 and uid = 'sM52xsvBYz3';
update dataelement set formname  = 'Number of twins عدد التوائم ' where dataelementid = 9129 and uid = 'obMbttnuVok';
update dataelement set formname  = 'Order amongst twins ترتيب ولادته بين التوائم' where dataelementid = 9130 and uid = 'vzeZEQ3bq21';
update dataelement set formname  = 'Gestational period (weeks) طول فترة الحمل بالأسابيع' where dataelementid = 9131 and uid = 'RlnT9J5A3wn';
update dataelement set formname  = 'Infant weight وزن المولود' where dataelementid = 9132 and uid = 'l2b4ogfp6Bw';
update dataelement set formname  = 'Health status الحالة الصحية للمولود' where dataelementid = 9133 and uid = 'QL9RuF9LW4w';
update dataelement set formname  = 'Mother''s name اسم الام' where dataelementid = 9134 and uid = 'w4EWn6HYkxO';
update dataelement set formname  = 'Mother''s ID/Passport number رقم البطاقة الشخصية/جواز السفر للام' where dataelementid = 9135 and uid = 'TaFhFmVE1tb';
update dataelement set formname  = 'Mother''s National ID الرقم الوطني للام' where dataelementid = 9136 and uid = 'zrBCRBiqyzy';
update dataelement set formname  = 'Mother''s nationality جنسية الام' where dataelementid = 9137 and uid = 'OsCI3nDRXMX';
update dataelement set formname  = 'Mother''s date of birth تاريخ ميلاد الام' where dataelementid = 9138 and uid = 'QnK7LQGwwIX';
update dataelement set formname  = 'Mother''s address-Area عنوان الام-المنطقة' where dataelementid = 9139 and uid = 'EXuDS5m8VGG';
update dataelement set formname  = 'Mother''s address-City عنوان الام-المدينة' where dataelementid = 9140 and uid = 'SBPFVBUM2o4';
update dataelement set formname  = 'Mother''s phone number رقم هااتف الام' where dataelementid = 9141 and uid = 'i5sz5DoJrEX';
update dataelement set formname  = 'Father''s name اسم الاب' where dataelementid = 9142 and uid = 'zfKSWsIgdfp';
update dataelement set formname  = 'Father''s ID/Passport number رقم البطاقة الشخصية/جواز السفر للاب' where dataelementid = 9143 and uid = 'crkH3nEVuG1';
update dataelement set formname  = 'Father''s National ID الرقم الوطني للاب' where dataelementid = 9144 and uid = 'fsm0pqyYQD8';
update dataelement set formname  = 'Father''s nationality جنسية الاب' where dataelementid = 9145 and uid = 'Wgfm2JCOTwa';
update dataelement set formname  = 'Father''s date of birth تاريخ ميلاد الاب' where dataelementid = 9146 and uid = 'vtMC8y2pOmG';
update dataelement set formname  = 'Father''s address-Area عنوان الاب-المنطقة' where dataelementid = 9147 and uid = 'TvVFYUMuGb5';
update dataelement set formname  = 'Father''s address-City عنوان الاب-المدينة' where dataelementid = 9148 and uid = 'l3PNTtyfItB';
update dataelement set formname  = 'Father''s phone number رقم هاتف الاب' where dataelementid = 9149 and uid = 'iYhYqb8TtB6';
update dataelement set formname  = 'Delivery attendant القائم بالتوليد' where dataelementid = 9150 and uid = 'RZLZ9T5pSjH';
update dataelement set formname  = 'Nutrition type رقم هااتف الام' where dataelementid = 50878 and uid = 'GLHqBOSNPD0';
update dataelement set formname  = 'Birth interval (years) اسم الاب' where dataelementid = 9151 and uid = 'RaPcRCdpx61';
update dataelement set formname  = 'Birth interval (months) رقم البطاقة الشخصية/جواز السفر للاب' where dataelementid = 9152 and uid = 'BDr5HEwYKWr';
update dataelement set formname  = 'Gravida الرقم الوطني للاب' where dataelementid = 9153 and uid = 'li8OsEoJ7jn';
update dataelement set formname  = 'Previous still births جنسية الاب' where dataelementid = 9154 and uid = 'S20LD7rwtbK';
update dataelement set formname  = 'Previous live births تاريخ ميلاد الاب' where dataelementid = 9155 and uid = 'OCF7bocjUGA';
update dataelement set formname  = 'Alive children (at present) عنوان الاب-المنطقة' where dataelementid = 9156 and uid = 't9j8cjlXjSJ';
update dataelement set formname  = 'Consanguinity عنوان الاب-المدينة' where dataelementid = 9157 and uid = 'I6KZEIsNulC';
update dataelement set formname  = 'Medication frequency I رقم هاتف الاب' where dataelementid = 8830 and uid = 'sOHbbEBSwgI';
update dataelement set formname  = 'Father''s occupation القائم بالتوليد' where dataelementid = 9204 and uid = 'qtc5D0HwJpF';
update dataelement set formname  = 'Mother''s occupation مهنة الام' where dataelementid = 9205 and uid = 'OzpwLOE654K';
update dataelement set formname  = 'City of birth مكان الميلاد' where dataelementid = 9324 and uid = 'UQ2rLrOdEv5';
update dataelement set formname  = 'Renal failure cause أسباب الفشل الكلوي' where dataelementid = 8801 and uid = 'iMOQ7kP1NSM';
update dataelement set formname  = 'Patient ID  هوية المريض' where dataelementid = 10081 and uid = 'sm6rhE9y9cn';
update dataelement set formname  = 'Height طول' where dataelementid = 10082 and uid = 'yyn9Xy91k3u';
update dataelement set formname  = 'Weight وزن' where dataelementid = 10083 and uid = 'AoDeAFlDyCC';
update dataelement set formname  = 'Degree of Malnutrition درجة سوء التغذية' where dataelementid = 10084 and uid = 'uneKxjdwTQt';
update dataelement set formname  = 'Malnutrition سوء التغذية' where dataelementid = 10103 and uid = 'aZZMEH6e98h';
update dataelement set formname  = 'Sample collection date حمل' where dataelementid = 12835 and uid = 'TulqV8CQRLE';
update dataelement set formname  = 'Referral facility (if referred) سوء التغذية' where dataelementid = 9121 and uid = 'SpWbZNhf4NX';
update dataelement set formname  = 'Needle type used نوع  ابرة التوصيل المستخدمة' where dataelementid = 8805 and uid = 'a8z5dMKeGgO';

end;